const PDFDocument = require('pdfkit');
const fs = require('fs');

const doc = new PDFDocument({ margin: 50 });
doc.pipe(fs.createWriteStream('NebulaStep_OTA_Deployment_Guide.pdf'));

// PDF Styling
doc.font('Helvetica-Bold').fontSize(24).fillColor('#00E5FF').text('NebulaStep', { align: 'center' });
doc.font('Helvetica-Bold').fontSize(18).fillColor('#333333').text('OTA Deployment Guide & Playbook', { align: 'center' });
doc.moveDown(2);

doc.font('Helvetica').fontSize(12).fillColor('#555555').text('This document outlines the official 5-step sequence required to push a new Over-The-Air (OTA) update directly to your userbase bypassing the Google Play Store.', { align: 'justify' });
doc.moveDown(2);

function createStep(stepNumber, title, description) {
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#000000').text(`Step ${stepNumber}: ${title}`);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(12).fillColor('#444444').text(description, { align: 'justify', continued: false });
    doc.moveDown(1.5);
}

createStep(1, 'Bump the Code Version', 'Inside your Android Studio project, open CustomUpdateEngine.kt. Change the `private const val CURRENT_VERSION = 1.0` flag to your new numerical version (e.g., 1.1). This triggers the update logic.');
createStep(2, 'Compile the Application (APK)', 'Navigate to Build > Build Bundle / APK(s) and select "Build APK(s)". Android Studio will generate the physical `.apk` installation file containing all your new code.');
createStep(3, 'Host the Download File', 'Upload your new `.apk` file to a public internet location so devices can grab it. You can place this file in Firebase Storage, an AWS S3 bucket, or your own personal website, and copy the direct download URL.');
createStep(4, 'Reconfigure the Firebase Database', 'Log back into your Firebase Console. Open Firestore Database and locate the `app_config/versions` global document. Update the `latest_version` number to match your code (1.1), and paste your hosted `.apk` link into the `download_url` field.');
createStep(5, 'The Global Rollout', 'The absolute second you hit "Save" on that Firebase document, the engine comes alive. The next time any user runs the app globally, they will be explicitly blocked by the "🚀 Major Update Available!" screen. The app will securely download the new version and auto-update itself seamlessly!');

// Footer
doc.moveDown(3);
doc.font('Helvetica-Oblique').fontSize(10).fillColor('#888888').text('Generated by your AI Architect for NebulaStep.', { align: 'center' });

doc.end();
